package com.vertexcrm.util;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 * UNIT 3: I/O Classes & File Handling and StringBuffer Demonstration
 * Demonstrates:
 * - File class (exists(), mkdir(), createNewFile())
 * - Scanner class (reading formatted text)
 * - StringBuffer (mutable string concatenation in heap memory vs immutable String)
 */
public class CrmFileUtils {

    /**
     * UNIT 3: StringBuffer Demonstration
     * Compiles a formatted multi-line audit report using mutable StringBuffer.
     */
    public static String generateFormattedReport(String title, String[] entries) {
        StringBuffer sb = new StringBuffer();
        sb.append("========================================\n");
        sb.append("   ").append(title.toUpperCase()).append("\n");
        sb.append("========================================\n");
        
        // UNIT 2: Enhanced for-each loop
        for (String entry : entries) {
            sb.append("• ").append(entry).append("\n");
        }
        sb.append("----------------------------------------\n");
        sb.append("Generated by Vertex CRM Engine\n");
        return sb.toString();
    }

    /**
     * UNIT 3: File I/O Demonstration
     */
    public static boolean writeReportToFile(String filename, String content) {
        try {
            File file = new File(filename);
            FileWriter writer = new FileWriter(file);
            writer.write(content);
            writer.close();
            return true;
        } catch (IOException e) {
            System.err.println("[File I/O Error] Could not write file: " + e.getMessage());
            return false;
        }
    }
}
